---
title: "Jilli Jung"
subtitle: "[Personal website](https://jillijung.github.io) | [Google Scholar](https://scholar.google.com/citations?user=7SVYZhEAAAAJ&hl=en) | Email: jpj5606@psu.edu"
date: September 9, 2024
date-format: long
format:
  pdf:
    colorlinks: true
    papersize: letter
    fontfamily: libertinus
    fontsize: 11pt
---

## EDUCATION

- **Ph.D. in Education Policy**, Pennsylvania State University (2021-2024)
    -   Dual-title in **Comparative and International Education**
    -   Minor in **Demography**

- **M.A. in Ethics Education**, Seoul National University (2017-2019)
    - **Exchange Student**, University of Oklahoma (Fall 2018)

- **B.A. in Ethics Education**, Minor: Sociology, Seoul National University (2013-2017)



## ACADEMIC EMPLOYMENT

- **Post-doctoral Researcher**, Stanford University (2024-)
- **Managing Editor**, American Journal of Education, Pennsylvania (2022-2024)
- **Researcher**, Korea Institute for Curriculum and Evaluation (2020)


## RESEARCH INTERESTS & TECHNICAL SKILLS

- **Research Interests**:  
    Education policy, Quantitative methods, Quasi-experimental methods, Gender, Socioeconomic, and racial/ethnic inequality, Large-scale datasets  

- **Technical Skills**:  
    R, STATA, QUARTO, MPLUS



## PEER-REVIEWED JOURNAL ARTICLES

* Gopalan, M., **Jung, J.**, Chiang, S., Linden-Carmichae, A., & Lanza, S. (Accepted). College Students’ Sense of Belonging and Alcohol Use amidst COVID-19: Evidence from a 21-day Daily Diary Study. *PloS one*.

* **Jung, J.**, & Fenelon, A. (2024). Do later school start times improve adolescents' sleep and substance use? A quasi-experimental study. *Preventive Medicine*, 185. https://doi.org/10.1016/j.ypmed.2024.108028.

* **Jung, J.**, & Gopalan, M. (2023). The Stubborn Unresponsiveness of Youth Voter Turnout to Civic Education: Quasi-experimental Evidence from State-Mandated Civics Tests. *Educational Evaluation and Policy Analysis*. https://doi.org/10.3102/01623737231195887
    * Policy Brief: [Scholars Strategy Network](https://scholars.org/contribution/state-mandated-civics-test-policy-does-not)
    * Media Coverage: [AERA Newsroom](https://www.aera.net/Newsroom/Study-Finds-That-State-Mandated-Civics-Test-Policy-Does-Not-Improve-Youth-Voter-Turnout), [Diverse](https://www.diverseeducation.com/reports-data/article/15546897/study-cei-civics-test-policy-ineffective-at-improving-youth-voter-turnout), Education Week [1](https://www.edweek.org/teaching-learning/this-popular-high-school-civics-requirement-doesnt-boost-voting-habits/2023/09) [2](https://www.edweek.org/teaching-learning/elections-depend-on-young-voters-can-civics-tests-drive-up-their-turnout/2022/11), [Enid News](https://www.enidnews.com/news/study-civics-tests-dont-improve-voter-turnout/article_ea1834f6-566d-11ee-ac7b-d37def1c8f6b.html), [EurekAlert!](https://www.eurekalert.org/news-releases/1001334), [KOSU – NPR](https://www.kosu.org/education/2023-09-19/civics-test-mandates-like-oklahomas-havent-improved-young-voter-turnout-study-finds), [News Wise](https://www.newswise.com/articles/study-finds-that-state-mandated-civics-test-policy-does-not-improve-youth-voter-turnout?sc=rsla), [Pennsylvania State University News](https://www.psu.edu/news/education/story/civics-test-policy-fails-increase-youth-voter-turnout-researchers-find/?utm_audience=Combined&utm_source=newswire&utm_medium=email&utm_campaign=Education%20Headlines&utm_content=10-25-2023-09-52&utm_term=Stories%20-%201), [Phys Org](https://phys.org/news/2023-09-state-mandated-civics-policy-youth-voter.html), [Science Magazine](https://scienmag.com/civics-test-policy-fails-to-increase-youth-voter-turnout-researchers-find/), and [WLRN](https://www.wlrn.org/elections-coverage/2023-09-18/florida-civics-engagement-voter-turnout-elections).

* Byun, S. Y., **Jung, J.**, & Shin, T. S. (2023). Does shadow education discourage or encourage creative thinking? Evidence from South Korea. Journal for the Study of Education and Development. *Journal for the Study of Education and Development*, 46(4), 774-808. https://doi.org/10.1080/02103702.2023.2230042
    * Best Paper Award 2023 in the thematic area of Applied Educational Research in the Journal for the Study of Education and Development

* Yi, H. J., Shin, Y. J., Min, Y., Jeong, J., **Jung, J.**, & Kang, Y. (2023). Perception and Experience of Sexual and Gender Minority Korean Youth in School Counseling. *International Journal for the Advancement of Counselling*, 45(2), 189-209. https://doi.org/10.1007/s10447-022-09490-0


### In Korean
* Byun, S., Park, S., & **Jung, J.** (2024). Socioeconomic Disparities in Korean Children's Expected Occupational Status: An International Comparative Perspective. *Korean Journal of Sociology of Education*, 34(2), 55-87. http://dx.doi.org/10.32465/ksocio.2024.34.2.003 

* Chung, H., Park, S., **Jung, J.**, & Byun, S., (2024). The effect of graduating from a private elementary school on college admissions results. *Korean Journal of Sociology of Education*, 34(1), 197-236. http://dx.doi.org/10.32465/ksocio.2024.34.1.007 

* Byun, S., Chung, H., & **Jung, J.** (2022). The effect of private elementary school attendance on the likelihood of attending elite high schools. *Korean Journal of Sociology of Education*, 32(1), 59-89. http://dx.doi.org/10.32465/ksocio.2022.32.1.003 
    * Media Coverage: [Kukminilbo](https://m.kmib.co.kr/view.asp?arcid=0018047828&code=61121111&sid1=soc)

* Kim, H., Yu, K., **Jung, J.** (2020). A longitudinal analysis of the characteristics of democratic citizens in South Korean moral education textbooks, 1973-2020. *Journal of Moral & Ethics Education*, 69, 375-410. http://dx.doi.org/10.18338/kojmee.2020..69.375 

* **Jung, J.**, & Hwang, S. (2020). The influence of family income on adolescents’ Grit: The mediation roles of extracurricular activities and parenting style. *Korean Journal of Youth Studies*, 27(11), 283-312. http://dx.doi.org/10.21509/KJYS.2020.11.27.11.283 

* **Jung, J.**, & Yu, K. (2020). The roles of national identity and intergroup contact on South Koreans’ attitudes toward North Korean defectors: A multicultural perspective. *Multicultural Education Studies*, 13(3), 85-111. http://dx.doi.org/10.14328/MES.2020.9.30.85 

* Kim, H., Yu, K., **Jung, J.**, Sin, J., & Kim, D. (2020). A longitudinal analysis of the contents of national and global citizenship in South Korean moral education textbooks, 1973-2020. *Journal of Moral & Ethics Education*, 68, 223-254. http://dx.doi.org/10.18338/kojmee.2020..68.223 

* **Jung, J.** (2019). Gender representation in middle school moral education textbooks in South Korea, 1973-2019. *Journal of Moral & Ethics Education*, 64, 241-270. http://dx.doi.org/10.18338/kojmee.2019..64.241 (in Korean)



## WORKING PAPERS AND MANUSCRIPTS UNDER REVIEW
* **Jung, J.** (Under review). Uncovering Absence Patterns among LGBTQ+ Students: Evidence from 190,000 Students in 2013–2020.

* Byun, S., Park, S., Chung, H., **Jung, J.**, Shin, T., & Kim, J. (Under review). Does Shadow Education Affect Behavioral (Dis)Engagement? Evidence from South Korean Elementary School Students.


## SELECTED CONFERENCE PRESENTATIONS
† Indicates first author presentation

- **2024**: Association for Education Finance and Policy†; American Educational Research Association†; Comparative and International Education Society; Population Association of America†; 
- **2023**: Association for Education Finance and Policy†; Association for Public Policy Analysis and Management†; European Association for Research on Learning and Instruction; IEA International Research Conference; Midwest Political Science Association†; Society for Research on Educational Effectiveness†; Southern Economic Association†
- **2022**: American Educational Research Association†; Comparative and International Education Society; Korean Education Longitudinal Study Conference; Pennsylvania State University College of Education Research Conference†
- **2021**: International Conference on Education Research†; Korean Education Longitudinal Study Conference; Pennsylvania State University College of Education Research Conference†; Seoul National University College of Education Research Conference; Society for the Psychological Study of Social Issues†
- **2020**: Comparative and International Education Society†; Korean Association for Multicultural Education International Conference†; Korean Children and Youth Panel Survey†; Korean Society for Moral & Ethics Education
- **2019**: Comparative and International Education Society†; Korean Society for Moral & Ethics Education



## INVITED TALKS

- **Jung, J.**, & Gopalan, M. (2024). The Stubborn Unresponsiveness of Youth Voter Turnout to Civic Education: Quasi-Experimental Evidence from State-Mandated Civics Tests. Paper presented at the winter collaborative meeting of the Council of Chief State School Officers. 
- **Jung, J.** (2023). The role of early childhood education coverage policies. Paper presented at the Comparative and International Education Speaker Series. Pennsylvania State University



## TEACHING EXPERIENCE

- **Teaching Assistant**, Education in American Society (Undergraduate course), Pennsylvania State University (2024 Spring and Summer)
- **Middle School Teacher**, Ethics 1 & 2, Munwon Middle School (2021)
- **Teaching Assistant**, Social Thought and Ethics (Undergraduate course) and North Korean Studies (Undergraduate course), Seoul National University (2017-2019)  



## SELECTED FELLOWSHIPS, SCHOLARSHIPS, AND AWARDS

- **SREE Researchers of Color Mentored Travel Award**, Society for Research on Educational Effectiveness (Cover registration, workshop, transportation, and accommodation) (2024)
- **AEFP Roe L. Johns Student Travel Grant**, Association for Education Finance and Policy ($400) (2024)
- **APPAM Equity and Inclusion Fellowship**, Association for Public Policy Analysis and Management (2023)
- **SREE Researchers of Color Mentored Travel Award**, Society for Research on Educational Effectiveness (2023)
- **Michael Salwen Scholarship**, Korean-American Educational Researchers Association ($500) (2023)
- **AERA Graduate Student Travel Award**, AERA International Studies SIG ($350) (2023)
- **AERA Graduate Student Travel Award**, AERA Division G ($95) (2023)
- **AEFP Roe L. Johns Student Travel Grant**, Association for Education Finance and Policy ($145) (2023)
- **California Health Interview Survey (CHIS) Data Student Scholarship**, UCLA Center for Health Policy Research ($500) (2023)
- **NAEP Data Training Workshop Award**, American Institutes for Research (2023)
- **Early Career Diversity Research Award**, Edna Bennett Pierce Prevention Research Center ($1,500) (2022-2023)  
  [Link to news article](https://prevention.psu.edu/news/prevention-research-center-funds-projects-promoting-the-health-of-diverse-groups/)
- **P.E.O. International Peace Scholarship**, P.E.O. ($9,000) (2022-2023)
- **CIED Summer Research Grant**, PSU Comparative and International Education Program ($1,000) (2022)
- **AERA Graduate Student Travel Award**, AERA International Studies SIG ($160) (2022)
- **Second Place**, Seoul National University College of Education Research Conference Award (2021)
- **Fulbright Graduate Student Program Alternate Candidate**, Fulbright Korea (2020)
- **Graduate Student Directed Research Grant**, Seoul National University (2019)
- **Fellowship for Next Generation Scholars**, Seoul National University (2017-2018)
- **ChungGuan Scholarship**, Seoul National University College of Education Alumni Association (2015)
- **SNU Merit-Based Scholarship**, Seoul National University (2014-2016)



## COMMUNITY SERVICE AND LEADERSHIP

- **Vice President**, Education Policy Studies Student Association, Pennsylvania State University (2023-2024)
- **Graduate Student Representative**, AERA International Studies SIG, American Educational Research Association (2023-2024)
- **Student President**, Department of Ethics Education, Seoul National University (2015)
- **Journal Referee**, Educational Researcher (2024, 2024), American Educational Research Association Conference Proposal (2022)



## PROFESSIONAL MEMBERSHIPS AND AFFILIATIONS

- Association for Education Finance & Policy (AEFP)
- American Educational Research Association (AERA)
- Association for Public Policy Analysis & Management (APPAM)
- Society for Research on Educational Effectiveness (SREE)